// <auto-generated />
using ADACA.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADACA.Migrations
{
    [DbContext(typeof(LoanContext))]
    [Migration("20230423115117_updateAmount")]
    partial class updateAmount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ADACA.Domain.Loan", b =>
                {
                    b.Property<int>("loanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loanId"), 1L, 1);

                    b.Property<string>("businessNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("citizen")
                        .HasColumnType("int");

                    b.Property<string>("countryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("loanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("timeTrading")
                        .HasColumnType("int");

                    b.HasKey("loanId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("ADACA.Domain.LoanAmountConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("aboveAmount")
                        .HasColumnType("int");

                    b.Property<int>("belowAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoanAmountConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            aboveAmount = 99999,
                            belowAmount = 10001
                        },
                        new
                        {
                            Id = 2,
                            aboveAmount = 2,
                            belowAmount = 19
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
